export type MediaItem = {
  file: string;
  thumb?: string;
  tags: string[];
  title?: string;
  description?: string;
};

export const mediaLibrary: MediaItem[] = [
  // ── detail/ items ──────────────────────────────────────────────────────────
  {
    file: '/media/portrait.webp',
    thumb: '/media/thumb_portrait.webp',
    tags: ['photo', 'business', 'startscreen'],
    title: 'Portrait',
    description: 'Business-Portrait von Michael Pzillas.',
  },
  {
    file: '/media/slider-start.png',
    thumb: '/media/thumb_slider-start.png',
    tags: ['startscreen'],
    title: 'Slider Start',
    description: 'Startscreen-Slider für die PIX-Website.',
  },
  {
    file: '/media/video-brand.webp',
    thumb: '/media/thumb_video-brand.webp',
    tags: ['video', 'brand', 'startscreen'],
    title: 'Imagefilm',
    description: 'Imagefilm-Produktion für Marken und Unternehmen.',
  },
  {
    file: '/media/video-drone.webp',
    thumb: '/media/thumb_video-drone.webp',
    tags: ['video', 'realestate'],
    title: 'Drohnenfilm',
    description: 'Drohnenaufnahmen für Immobilienpräsentationen und Exposés.',
  },
  {
    file: '/media/video-event.webp',
    thumb: '/media/thumb_video-event.webp',
    tags: ['video', 'event'],
    title: 'Eventfilm',
    description: 'Eventfilme die Atmosphäre und Momente einfangen.',
  },
  {
    file: '/media/video-konferenz.webp',
    thumb: '/media/thumb_video-konferenz.webp',
    tags: ['video', 'event'],
    title: 'Konferenzfilm',
    description: 'Videodokumentation von Konferenzen und Fachveranstaltungen.',
  },
  {
    file: '/media/video-lab.webp',
    thumb: '/media/thumb_video-lab.webp',
    tags: ['video', 'brand'],
    title: 'Laborfilm',
    description: 'Corporate Video für Forschungs- und Laborumgebungen.',
  },
  {
    file: '/media/video-motion.webp',
    thumb: '/media/thumb_video-motion.webp',
    tags: ['video', 'brand'],
    title: 'Motion Design',
    description: 'Animationen und Motion-Design für Branding und Social Media.',
  },
  {
    file: '/media/video-social.webp',
    thumb: '/media/thumb_video-social.webp',
    tags: ['video', 'brand'],
    title: 'Social Media Video',
    description: 'Kurzvideos für Instagram, LinkedIn und andere Social-Media-Plattformen.',
  },
  {
    file: '/media/video-story.webp',
    thumb: '/media/thumb_video-story.webp',
    tags: ['video', 'brand'],
    title: 'Storytelling Film',
    description: 'Storytelling-Formate die Unternehmenswerte und Visionen transportieren.',
  },
  {
    file: '/media/event-foto.webp',
    thumb: '/media/thumb_event-foto.webp',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Professionelle Eventfotografie für Firmenveranstaltungen und Messen.',
  },
  {
    file: '/media/konferenz-foto.webp',
    thumb: '/media/thumb_konferenz-foto.webp',
    tags: ['photo', 'event'],
    title: 'Konferenzfotografie',
    description: 'Reportage-Fotografie von Konferenzen, Panels und Keynotes.',
  },
  {
    file: '/media/immo-architektur.webp',
    thumb: '/media/thumb_immo-architektur.webp',
    tags: ['photo', 'realestate', 'architektur'],
    title: 'Architektur & Immobilien',
    description: 'Architekturfotografie für Immobilien mit Fokus auf Struktur und Material.',
  },
  {
    file: '/media/immo-detail.webp',
    thumb: '/media/thumb_immo-detail.webp',
    tags: ['photo', 'realestate'],
    title: 'Immobilien Detailaufnahme',
    description: 'Detailfotografie von Ausstattung und besonderen Merkmalen einer Immobilie.',
  },
  {
    file: '/media/immo-holzbau.webp',
    thumb: '/media/thumb_immo-holzbau.webp',
    tags: ['photo', 'realestate'],
    title: 'Holzbau Immobilienfotografie',
    description: 'Fotografie eines Holzbau-Projekts für das Exposé.',
  },
  {
    file: '/media/immo-interieur.webp',
    thumb: '/media/thumb_immo-interieur.webp',
    tags: ['photo', 'realestate'],
    title: 'Interieur Immobilienfotografie',
    description: 'Innenraumaufnahmen für Wohnimmobilien und Neubauprojekte.',
  },
  {
    file: '/media/immo-tageslicht.webp',
    thumb: '/media/thumb_immo-tageslicht.webp',
    tags: ['photo', 'realestate'],
    title: 'Tageslichtaufnahmen Immobilien',
    description: 'Immobilienfotografie im natürlichen Tageslicht für optimale Wirkung.',
  },
  {
    file: '/media/offenblende-fassade.webp',
    thumb: '/media/thumb_offenblende-fassade.webp',
    tags: ['photo', 'realestate', 'architektur'],
    title: 'Fassadenaufnahme',
    description: 'Architekturfotografie von Fassaden und Außenansichten.',
  },
  {
    file: '/media/offenblende-haus.webp',
    thumb: '/media/thumb_offenblende-haus.webp',
    tags: ['photo', 'realestate'],
    title: 'Hausaufnahme',
    description: 'Außenfotografie von Wohnhäusern und Mehrfamilienhäusern.',
  },
  {
    file: '/media/offenblende-produkt.webp',
    thumb: '/media/thumb_offenblende-produkt.webp',
    tags: ['photo', 'realestate'],
    title: 'Produktfotografie Immobilien',
    description: 'Hochwertige Produktfotografie im Immobilienkontext.',
  },
  {
    file: '/media/moos.webp',
    thumb: '/media/thumb_moos.webp',
    tags: ['web', 'tools'],
    title: 'EV Moosburg',
    description: 'Ticketing- und Spielplan-Plattform für den Eishockeyverein EV Moosburg.',
  },
  {
    file: '/media/booking.webp',
    thumb: '/media/thumb_booking.webp',
    tags: ['web', 'tools'],
    title: 'Buchungssystem',
    description: 'Web-Interface eines Buchungs- und Terminverwaltungssystems.',
  },
  {
    file: '/media/dashboard.webp',
    thumb: '/media/thumb_dashboard.webp',
    tags: ['web', 'tools'],
    title: 'Dashboard UI',
    description: 'Übersichtliches Dashboard-Interface für Datenverwaltung und Auswertung.',
  },
  {
    file: '/media/interface.webp',
    thumb: '/media/thumb_interface.webp',
    tags: ['web', 'tools'],
    title: 'Web Interface',
    description: 'Modernes UI-Design für eine Web-Applikation.',
  },
  {
    file: '/media/jakobs-app.webp',
    thumb: '/media/thumb_jakobs-app.webp',
    tags: ['web', 'business'],
    title: 'Jakobs App',
    description: 'App-Interface für Jakobs Consulting mit Fokus auf Nutzererfahrung.',
  },
  {
    file: '/media/jakobs.webp',
    thumb: '/media/thumb_jakobs.webp',
    tags: ['web', 'business'],
    title: 'Jakobs Consulting Website',
    description: 'Unternehmenswebsite für Jakobs Consulting.',
  },
  {
    file: '/media/leasehub.webp',
    thumb: '/media/thumb_leasehub.webp',
    tags: ['web', 'tools'],
    title: 'LeaseHub',
    description: 'SaaS-Plattform für Fahrzeug-Leasingverwaltung.',
  },
  {
    file: '/media/qr-tool.webp',
    thumb: '/media/thumb_qr-tool.webp',
    tags: ['web', 'tools'],
    title: 'QR-Tool',
    description: 'Web-Tool zur Erstellung und Verwaltung von QR-Codes.',
  },
  {
    file: '/media/system.webp',
    thumb: '/media/thumb_system.webp',
    tags: ['web', 'tools'],
    title: 'System Interface',
    description: 'Backend-System und Verwaltungs-Interface für komplexe Datenprozesse.',
  },

  // ── foto-hd/ items ─────────────────────────────────────────────────────────
  {
    file: '/media/hd_1_business.webp',
    thumb: '/media/sq_1_business.webp',
    tags: ['photo', 'business', 'startscreen'],
    title: 'Business Portrait',
    description: 'Business-Portrait für Führungskräfte und Unternehmer.',
  },
  {
    file: '/media/hd_2_immobilien.webp',
    thumb: '/media/sq_2_immobilien.webp',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Hochwertige Immobilienfotografie für Exposés und Vermarktung.',
  },
  {
    file: '/media/hd_3_architektur.jpg',
    thumb: '/media/sq_3_architektur.jpg',
    tags: ['photo', 'architektur'],
    title: 'Architekturfotografie',
    description: 'Architekturfotografie im Rhein-Main-Gebiet.',
  },
  {
    file: '/media/hd_4_immobilien.jpg',
    thumb: '/media/sq_4_immobilien.jpg',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Exposé-Fotografie für Wohnimmobilien.',
  },
  {
    file: '/media/hd_5_immobilien.jpg',
    thumb: '/media/sq_5_immobilien.jpg',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Innenraumaufnahmen für ein Immobilien-Exposé.',
  },
  {
    file: '/media/hd_6_immobilien.jpg',
    thumb: '/media/sq_6_immobilien.jpg',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Wohnraumfotografie für eine Eigentumswohnung.',
  },
  {
    file: '/media/hd_7_immobilien.jpg',
    thumb: '/media/sq_7_immobilien.jpg',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Lichtdurchflutete Innenraumfotografie für eine Wohnimmobilie.',
  },
  {
    file: '/media/hd_8_immobilien.jpg',
    thumb: '/media/sq_8_immobilien.jpg',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Detailreiche Raumaufnahmen für ein Immobilien-Exposé.',
  },
  {
    file: '/media/hd_9_architektur.jpg',
    thumb: '/media/sq_9_architektur.jpg',
    tags: ['photo', 'architektur'],
    title: 'Architekturfotografie',
    description: 'Außenansicht eines modernen Gebäudes.',
  },
  {
    file: '/media/hd_10_architektur.jpg',
    thumb: '/media/sq_10_architektur.jpg',
    tags: ['photo', 'architektur'],
    title: 'Architekturfotografie',
    description: 'Architekturfotografie mit Fokus auf Linien und Perspektiven.',
  },
  {
    file: '/media/hd_11_immobilien.png',
    thumb: '/media/sq_11_immobilien.png',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Professionelle Wohnraumfotografie für die Immobilienvermarktung.',
  },
  {
    file: '/media/hd_12_event.jpg',
    thumb: '/media/sq_12_event.jpg',
    tags: ['photo', 'event', 'startscreen'],
    title: '600 Kids Festival',
    description: 'Eventfotografie für das 600 Kids Jugendfestival in Frankfurt.',
  },
  {
    file: '/media/hd_13_event.jpg',
    thumb: '/media/sq_13_event.jpg',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Reportage-Fotografie von einem Firmen-Event.',
  },
  {
    file: '/media/hd_14_event.webp',
    thumb: '/media/sq_14_event.webp',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Stimmungsvolle Eventfotografie mit natürlichem Licht.',
  },
  {
    file: '/media/hd_15_event.webp',
    thumb: '/media/sq_15_event.webp',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Dynamische Eventfotografie für Veranstaltungen und Messen.',
  },
  {
    file: '/media/hd_16_event.jpg',
    thumb: '/media/sq_16_event.jpg',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Spontane Momentaufnahmen von einem Networking-Event.',
  },
  {
    file: '/media/hd_17_business.webp',
    thumb: '/media/sq_17_business.webp',
    tags: ['photo', 'business'],
    title: 'Business Fotografie',
    description: 'Professionelle Business-Fotografie für Corporate-Auftritte.',
  },
  {
    file: '/media/hd_18_business.webp',
    thumb: '/media/sq_18_business.webp',
    tags: ['photo', 'business'],
    title: 'Business Fotografie',
    description: 'Team- und Mitarbeiterportraits für Unternehmenskommunikation.',
  },
  {
    file: '/media/hd_19_menschen.webp',
    thumb: '/media/sq_19_menschen.webp',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Authentische Personenfotografie in natürlicher Umgebung.',
  },
  {
    file: '/media/hd_20_menschen.jpg',
    thumb: '/media/sq_20_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Porträt mit Fokus auf Persönlichkeit und Ausdruck.',
  },
  {
    file: '/media/hd_21_menschen.jpg',
    thumb: '/media/sq_21_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Lebendige Personenfotografie in urbaner Umgebung.',
  },
  {
    file: '/media/hd_22_menschen.jpg',
    thumb: '/media/sq_22_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Emotionales Portrait mit natürlichem Licht.',
  },
  {
    file: '/media/hd_23_menschen.jpg',
    thumb: '/media/sq_23_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Porträtserie mit authentischem Charakter.',
  },
  {
    file: '/media/hd_24_menschen.jpg',
    thumb: '/media/sq_24_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Menschen in Bewegung — lebendig und ungeplant.',
  },
  {
    file: '/media/hd_25_menschen.jpg',
    thumb: '/media/sq_25_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Stimmungsvolles Portrait mit bewusstem Hintergrund.',
  },
  {
    file: '/media/hd_26_business.jpg',
    thumb: '/media/sq_26_business.jpg',
    tags: ['photo', 'business'],
    title: 'Business Fotografie',
    description: 'Business-Portrait in professionellem Umfeld.',
  },
  {
    file: '/media/hd_27_business.jpg',
    thumb: '/media/sq_27_business.jpg',
    tags: ['photo', 'business'],
    title: 'Business Fotografie',
    description: 'Unternehmensportrait für Website und LinkedIn.',
  },
  {
    file: '/media/hd_28_business.jpg',
    thumb: '/media/sq_28_business.jpg',
    tags: ['photo', 'business'],
    title: 'Business Fotografie',
    description: 'Professionelles Portrait für Führungskräfte.',
  },
  {
    file: '/media/hd_29_event.jpg',
    thumb: '/media/sq_29_event.jpg',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Dokumentarische Eventfotografie von einer Firmenveranstaltung.',
  },
  {
    file: '/media/hd_30_architektur.jpg',
    thumb: '/media/sq_30_architektur.jpg',
    tags: ['photo', 'architektur'],
    title: 'Architekturfotografie',
    description: 'Architekturfotografie mit dramatischen Perspektiven.',
  },

  // ── web-projects/ cover items ──────────────────────────────────────────────
  {
    file: '/media/web_leasehub_cover.webp',
    thumb: '/media/web_leasehub_cover.webp',
    tags: ['web', 'tools', 'startscreen'],
    title: 'LeaseHub',
    description: 'SaaS-Plattform für Fahrzeug-Leasingverwaltung. Dashboard, Kundenzugang und Vertragsverwaltung.',
  },
  {
    file: '/media/web_crewting_cover.webp',
    thumb: '/media/web_crewting_cover.webp',
    tags: ['web', 'tools'],
    title: 'Crewting',
    description: 'Matching-App für Kreativteams und Freelancer.',
  },
  {
    file: '/media/web_jakobs_cover.webp',
    thumb: '/media/web_jakobs_cover.webp',
    tags: ['web', 'business', 'startscreen'],
    title: 'Jakobs Consulting',
    description: 'Unternehmensauftritt für eine Unternehmensberatung.',
  },
  {
    file: '/media/web_pms_cover.webp',
    thumb: '/media/web_pms_cover.webp',
    tags: ['web', 'tools'],
    title: 'PMS',
    description: 'Property Management System für Immobilienverwaltung.',
  },
  {
    file: '/media/web_tososto_cover.webp',
    thumb: '/media/web_tososto_cover.webp',
    tags: ['web', 'tools'],
    title: 'Tososto',
    description: 'Inserat-Plattform mit Kartenansicht und E-Mail-Integration.',
  },
  {
    file: '/media/web_600kids_cover.webp',
    thumb: '/media/web_600kids_cover.webp',
    tags: ['web', 'landing'],
    title: '600 Kids',
    description: 'Festival-Webseite für ein Jugendfestival in Frankfurt.',
  },
];

export function getMediaByTags(tags: string[]): string[] {
  if (!tags.length) return [];
  // Primär: Bilder die ALLE Tags haben (am spezifischsten)
  const andMatch = mediaLibrary.filter(item => tags.every(t => item.tags.includes(t)));
  if (andMatch.length >= 3) return andMatch.map(item => item.file);
  // Zu wenige Treffer → breiter: Bilder die IRGENDEINEN Tag haben.
  // AND-Treffer zuerst, dann der Rest — so bleibt es relevant, aber gefüllt.
  const anyMatch = mediaLibrary.filter(item => tags.some(t => item.tags.includes(t)));
  const ordered = [...andMatch, ...anyMatch.filter(item => !andMatch.includes(item))];
  return ordered.map(item => item.file);
}
