export type MediaItem = {
  file: string;
  thumb?: string;
  tags: string[];
  title?: string;
  description?: string;
};

export const mediaLibrary: MediaItem[] = [
  // ── detail/ items ──────────────────────────────────────────────────────────
  {
    file: '/media/detail/portrait.webp',
    thumb: '/media/thumbs/portrait.webp',
    tags: ['photo', 'business', 'startscreen'],
    title: 'Portrait',
    description: 'Business-Portrait von Michael Pzillas.',
  },
  {
    file: '/media/detail/slider-start.png',
    thumb: '/media/thumbs/slider-start.png',
    tags: ['startscreen'],
    title: 'Slider Start',
    description: 'Startscreen-Slider für die PIX-Website.',
  },
  {
    file: '/media/detail/video-brand.webp',
    thumb: '/media/thumbs/video-brand.webp',
    tags: ['video', 'brand', 'startscreen'],
    title: 'Imagefilm',
    description: 'Imagefilm-Produktion für Marken und Unternehmen.',
  },
  {
    file: '/media/detail/video-drone.webp',
    thumb: '/media/thumbs/video-drone.webp',
    tags: ['video', 'realestate'],
    title: 'Drohnenfilm',
    description: 'Drohnenaufnahmen für Immobilienpräsentationen und Exposés.',
  },
  {
    file: '/media/detail/video-event.webp',
    thumb: '/media/thumbs/video-event.webp',
    tags: ['video', 'event'],
    title: 'Eventfilm',
    description: 'Eventfilme die Atmosphäre und Momente einfangen.',
  },
  {
    file: '/media/detail/video-konferenz.webp',
    thumb: '/media/thumbs/video-konferenz.webp',
    tags: ['video', 'event'],
    title: 'Konferenzfilm',
    description: 'Videodokumentation von Konferenzen und Fachveranstaltungen.',
  },
  {
    file: '/media/detail/video-lab.webp',
    thumb: '/media/thumbs/video-lab.webp',
    tags: ['video', 'brand'],
    title: 'Laborfilm',
    description: 'Corporate Video für Forschungs- und Laborumgebungen.',
  },
  {
    file: '/media/detail/video-motion.webp',
    thumb: '/media/thumbs/video-motion.webp',
    tags: ['video', 'brand'],
    title: 'Motion Design',
    description: 'Animationen und Motion-Design für Branding und Social Media.',
  },
  {
    file: '/media/detail/video-social.webp',
    thumb: '/media/thumbs/video-social.webp',
    tags: ['video', 'brand'],
    title: 'Social Media Video',
    description: 'Kurzvideos für Instagram, LinkedIn und andere Social-Media-Plattformen.',
  },
  {
    file: '/media/detail/video-story.webp',
    thumb: '/media/thumbs/video-story.webp',
    tags: ['video', 'brand'],
    title: 'Storytelling Film',
    description: 'Storytelling-Formate die Unternehmenswerte und Visionen transportieren.',
  },
  {
    file: '/media/detail/event-foto.webp',
    thumb: '/media/thumbs/event-foto.webp',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Professionelle Eventfotografie für Firmenveranstaltungen und Messen.',
  },
  {
    file: '/media/detail/konferenz-foto.webp',
    thumb: '/media/thumbs/konferenz-foto.webp',
    tags: ['photo', 'event'],
    title: 'Konferenzfotografie',
    description: 'Reportage-Fotografie von Konferenzen, Panels und Keynotes.',
  },
  {
    file: '/media/detail/immo-architektur.webp',
    thumb: '/media/thumbs/immo-architektur.webp',
    tags: ['photo', 'realestate', 'architektur'],
    title: 'Architektur & Immobilien',
    description: 'Architekturfotografie für Immobilien mit Fokus auf Struktur und Material.',
  },
  {
    file: '/media/detail/immo-detail.webp',
    thumb: '/media/thumbs/immo-detail.webp',
    tags: ['photo', 'realestate'],
    title: 'Immobilien Detailaufnahme',
    description: 'Detailfotografie von Ausstattung und besonderen Merkmalen einer Immobilie.',
  },
  {
    file: '/media/detail/immo-holzbau.webp',
    thumb: '/media/thumbs/immo-holzbau.webp',
    tags: ['photo', 'realestate'],
    title: 'Holzbau Immobilienfotografie',
    description: 'Fotografie eines Holzbau-Projekts für das Exposé.',
  },
  {
    file: '/media/detail/immo-interieur.webp',
    thumb: '/media/thumbs/immo-interieur.webp',
    tags: ['photo', 'realestate'],
    title: 'Interieur Immobilienfotografie',
    description: 'Innenraumaufnahmen für Wohnimmobilien und Neubauprojekte.',
  },
  {
    file: '/media/detail/immo-tageslicht.webp',
    thumb: '/media/thumbs/immo-tageslicht.webp',
    tags: ['photo', 'realestate'],
    title: 'Tageslichtaufnahmen Immobilien',
    description: 'Immobilienfotografie im natürlichen Tageslicht für optimale Wirkung.',
  },
  {
    file: '/media/detail/offenblende-fassade.webp',
    thumb: '/media/thumbs/offenblende-fassade.webp',
    tags: ['photo', 'realestate', 'architektur'],
    title: 'Fassadenaufnahme',
    description: 'Architekturfotografie von Fassaden und Außenansichten.',
  },
  {
    file: '/media/detail/offenblende-haus.webp',
    thumb: '/media/thumbs/offenblende-haus.webp',
    tags: ['photo', 'realestate'],
    title: 'Hausaufnahme',
    description: 'Außenfotografie von Wohnhäusern und Mehrfamilienhäusern.',
  },
  {
    file: '/media/detail/offenblende-produkt.webp',
    thumb: '/media/thumbs/offenblende-produkt.webp',
    tags: ['photo', 'realestate'],
    title: 'Produktfotografie Immobilien',
    description: 'Hochwertige Produktfotografie im Immobilienkontext.',
  },
  {
    file: '/media/detail/moos.webp',
    thumb: '/media/thumbs/moos.webp',
    tags: ['photo', 'architektur'],
    title: 'Architekturfotografie Moos',
    description: 'Detailreiche Architekturfotografie von natürlichen Oberflächenstrukturen.',
  },
  {
    file: '/media/detail/booking.webp',
    thumb: '/media/thumbs/booking.webp',
    tags: ['web', 'tools'],
    title: 'Buchungssystem',
    description: 'Web-Interface eines Buchungs- und Terminverwaltungssystems.',
  },
  {
    file: '/media/detail/dashboard.webp',
    thumb: '/media/thumbs/dashboard.webp',
    tags: ['web', 'tools'],
    title: 'Dashboard UI',
    description: 'Übersichtliches Dashboard-Interface für Datenverwaltung und Auswertung.',
  },
  {
    file: '/media/detail/interface.webp',
    thumb: '/media/thumbs/interface.webp',
    tags: ['web', 'tools'],
    title: 'Web Interface',
    description: 'Modernes UI-Design für eine Web-Applikation.',
  },
  {
    file: '/media/detail/jakobs-app.webp',
    thumb: '/media/thumbs/jakobs-app.webp',
    tags: ['web', 'business'],
    title: 'Jakobs App',
    description: 'App-Interface für Jakobs Consulting mit Fokus auf Nutzererfahrung.',
  },
  {
    file: '/media/detail/jakobs.webp',
    thumb: '/media/thumbs/jakobs.webp',
    tags: ['web', 'business'],
    title: 'Jakobs Consulting Website',
    description: 'Unternehmenswebsite für Jakobs Consulting.',
  },
  {
    file: '/media/detail/leasehub.webp',
    thumb: '/media/thumbs/leasehub.webp',
    tags: ['web', 'tools'],
    title: 'LeaseHub',
    description: 'SaaS-Plattform für Fahrzeug-Leasingverwaltung.',
  },
  {
    file: '/media/detail/qr-tool.webp',
    thumb: '/media/thumbs/qr-tool.webp',
    tags: ['web', 'tools'],
    title: 'QR-Tool',
    description: 'Web-Tool zur Erstellung und Verwaltung von QR-Codes.',
  },
  {
    file: '/media/detail/system.webp',
    thumb: '/media/thumbs/system.webp',
    tags: ['web', 'tools'],
    title: 'System Interface',
    description: 'Backend-System und Verwaltungs-Interface für komplexe Datenprozesse.',
  },

  // ── foto-hd/ items ─────────────────────────────────────────────────────────
  {
    file: '/media/foto-hd/1_business.webp',
    thumb: '/media/foto-square/1_business.webp',
    tags: ['photo', 'business', 'startscreen'],
    title: 'Business Portrait',
    description: 'Business-Portrait für Führungskräfte und Unternehmer.',
  },
  {
    file: '/media/foto-hd/2_immobilien.webp',
    thumb: '/media/foto-square/2_immobilien.webp',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Hochwertige Immobilienfotografie für Exposés und Vermarktung.',
  },
  {
    file: '/media/foto-hd/3_architektur.jpg',
    thumb: '/media/foto-square/3_architektur.jpg',
    tags: ['photo', 'architektur'],
    title: 'Architekturfotografie',
    description: 'Architekturfotografie im Rhein-Main-Gebiet.',
  },
  {
    file: '/media/foto-hd/4_immobilien.jpg',
    thumb: '/media/foto-square/4_immobilien.jpg',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Exposé-Fotografie für Wohnimmobilien.',
  },
  {
    file: '/media/foto-hd/5_immobilien.jpg',
    thumb: '/media/foto-square/5_immobilien.jpg',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Innenraumaufnahmen für ein Immobilien-Exposé.',
  },
  {
    file: '/media/foto-hd/6_immobilien.jpg',
    thumb: '/media/foto-square/6_immobilien.jpg',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Wohnraumfotografie für eine Eigentumswohnung.',
  },
  {
    file: '/media/foto-hd/7_immobilien.jpg',
    thumb: '/media/foto-square/7_immobilien.jpg',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Lichtdurchflutete Innenraumfotografie für eine Wohnimmobilie.',
  },
  {
    file: '/media/foto-hd/8_immobilien.jpg',
    thumb: '/media/foto-square/8_immobilien.jpg',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Detailreiche Raumaufnahmen für ein Immobilien-Exposé.',
  },
  {
    file: '/media/foto-hd/9_architektur.jpg',
    thumb: '/media/foto-square/9_architektur.jpg',
    tags: ['photo', 'architektur'],
    title: 'Architekturfotografie',
    description: 'Außenansicht eines modernen Gebäudes.',
  },
  {
    file: '/media/foto-hd/10_architektur.jpg',
    thumb: '/media/foto-square/10_architektur.jpg',
    tags: ['photo', 'architektur'],
    title: 'Architekturfotografie',
    description: 'Architekturfotografie mit Fokus auf Linien und Perspektiven.',
  },
  {
    file: '/media/foto-hd/11_immobilien.png',
    thumb: '/media/foto-square/11_immobilien.png',
    tags: ['photo', 'realestate'],
    title: 'Immobilienfotografie',
    description: 'Professionelle Wohnraumfotografie für die Immobilienvermarktung.',
  },
  {
    file: '/media/foto-hd/12_event.jpg',
    thumb: '/media/foto-square/12_event.jpg',
    tags: ['photo', 'event', 'startscreen'],
    title: '600 Kids Festival',
    description: 'Eventfotografie für das 600 Kids Jugendfestival in Frankfurt.',
  },
  {
    file: '/media/foto-hd/13_event.jpg',
    thumb: '/media/foto-square/13_event.jpg',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Reportage-Fotografie von einem Firmen-Event.',
  },
  {
    file: '/media/foto-hd/14_event.webp',
    thumb: '/media/foto-square/14_event.webp',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Stimmungsvolle Eventfotografie mit natürlichem Licht.',
  },
  {
    file: '/media/foto-hd/15_event.webp',
    thumb: '/media/foto-square/15_event.webp',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Dynamische Eventfotografie für Veranstaltungen und Messen.',
  },
  {
    file: '/media/foto-hd/16_event.jpg',
    thumb: '/media/foto-square/16_event.jpg',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Spontane Momentaufnahmen von einem Networking-Event.',
  },
  {
    file: '/media/foto-hd/17_business.webp',
    thumb: '/media/foto-square/17_business.webp',
    tags: ['photo', 'business'],
    title: 'Business Fotografie',
    description: 'Professionelle Business-Fotografie für Corporate-Auftritte.',
  },
  {
    file: '/media/foto-hd/18_business.webp',
    thumb: '/media/foto-square/18_business.webp',
    tags: ['photo', 'business'],
    title: 'Business Fotografie',
    description: 'Team- und Mitarbeiterportraits für Unternehmenskommunikation.',
  },
  {
    file: '/media/foto-hd/19_menschen.webp',
    thumb: '/media/foto-square/19_menschen.webp',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Authentische Personenfotografie in natürlicher Umgebung.',
  },
  {
    file: '/media/foto-hd/20_menschen.jpg',
    thumb: '/media/foto-square/20_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Porträt mit Fokus auf Persönlichkeit und Ausdruck.',
  },
  {
    file: '/media/foto-hd/21_menschen.jpg',
    thumb: '/media/foto-square/21_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Lebendige Personenfotografie in urbaner Umgebung.',
  },
  {
    file: '/media/foto-hd/22_menschen.jpg',
    thumb: '/media/foto-square/22_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Emotionales Portrait mit natürlichem Licht.',
  },
  {
    file: '/media/foto-hd/23_menschen.jpg',
    thumb: '/media/foto-square/23_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Porträtserie mit authentischem Charakter.',
  },
  {
    file: '/media/foto-hd/24_menschen.jpg',
    thumb: '/media/foto-square/24_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Menschen in Bewegung — lebendig und ungeplant.',
  },
  {
    file: '/media/foto-hd/25_menschen.jpg',
    thumb: '/media/foto-square/25_menschen.jpg',
    tags: ['photo', 'menschen'],
    title: 'Menschenfotografie',
    description: 'Stimmungsvolles Portrait mit bewusstem Hintergrund.',
  },
  {
    file: '/media/foto-hd/26_business.jpg',
    thumb: '/media/foto-square/26_business.jpg',
    tags: ['photo', 'business'],
    title: 'Business Fotografie',
    description: 'Business-Portrait in professionellem Umfeld.',
  },
  {
    file: '/media/foto-hd/27_business.jpg',
    thumb: '/media/foto-square/27_business.jpg',
    tags: ['photo', 'business'],
    title: 'Business Fotografie',
    description: 'Unternehmensportrait für Website und LinkedIn.',
  },
  {
    file: '/media/foto-hd/28_business.jpg',
    thumb: '/media/foto-square/28_business.jpg',
    tags: ['photo', 'business'],
    title: 'Business Fotografie',
    description: 'Professionelles Portrait für Führungskräfte.',
  },
  {
    file: '/media/foto-hd/29_event.jpg',
    thumb: '/media/foto-square/29_event.jpg',
    tags: ['photo', 'event'],
    title: 'Eventfotografie',
    description: 'Dokumentarische Eventfotografie von einer Firmenveranstaltung.',
  },
  {
    file: '/media/foto-hd/30_architektur.jpg',
    thumb: '/media/foto-square/30_architektur.jpg',
    tags: ['photo', 'architektur'],
    title: 'Architekturfotografie',
    description: 'Architekturfotografie mit dramatischen Perspektiven.',
  },

  // ── web-projects/ cover items ──────────────────────────────────────────────
  {
    file: '/media/web-projects/leasehub/cover.webp',
    thumb: '/media/web-projects/leasehub/cover.webp',
    tags: ['web', 'tools', 'startscreen'],
    title: 'LeaseHub',
    description: 'SaaS-Plattform für Fahrzeug-Leasingverwaltung. Dashboard, Kundenzugang und Vertragsverwaltung.',
  },
  {
    file: '/media/web-projects/crewting/cover.webp',
    thumb: '/media/web-projects/crewting/cover.webp',
    tags: ['web', 'tools'],
    title: 'Crewting',
    description: 'Matching-App für Kreativteams und Freelancer.',
  },
  {
    file: '/media/web-projects/jakobs/cover.webp',
    thumb: '/media/web-projects/jakobs/cover.webp',
    tags: ['web', 'business', 'startscreen'],
    title: 'Jakobs Consulting',
    description: 'Unternehmensauftritt für eine Unternehmensberatung.',
  },
  {
    file: '/media/web-projects/pms/cover.webp',
    thumb: '/media/web-projects/pms/cover.webp',
    tags: ['web', 'tools'],
    title: 'PMS',
    description: 'Property Management System für Immobilienverwaltung.',
  },
  {
    file: '/media/web-projects/tososto/cover.webp',
    thumb: '/media/web-projects/tososto/cover.webp',
    tags: ['web', 'tools'],
    title: 'Tososto',
    description: 'Inserat-Plattform mit Kartenansicht und E-Mail-Integration.',
  },
  {
    file: '/media/web-projects/600kids/cover.webp',
    thumb: '/media/web-projects/600kids/cover.webp',
    tags: ['web', 'landing'],
    title: '600 Kids',
    description: 'Festival-Webseite für ein Jugendfestival in Frankfurt.',
  },
];

export function getMediaByTags(tags: string[]): string[] {
  return mediaLibrary
    .filter(item => tags.every(t => item.tags.includes(t)))
    .map(item => item.file);
}
